FROM 442386744353.dkr.ecr.us-gov-west-1.amazonaws.com/huggingface-pytorch-inference@sha256:44ba8a83e84ec5cbbc05181ff21cad1dc9bbd592abf0584d1d382bddc2a62cec

RUN python -m pip install --no-cache-dir \
      accelerate==1.14.0 \
      peft==0.17.1 \
      safetensors==0.8.0 \
      sentencepiece==0.2.2 \
      transformers==4.57.6 \
    && python -m pip check
