import { cleanup, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import App from './App'
import { apiClient } from './api/client'

// Isolated UI fixtures, never included in deployed workspace data.
const doc = { id: 'document-1', kind: 'document', title: 'Uploaded agreement', text: 'The supplier warrants the original equipment for twelve months. '.repeat(3), category: 'contract', version: 'v1', metadata: null, revision: 1, owner: 'reviewer', created_at: '2026-09-08T12:00:00Z', updated_at: '2026-09-08T12:00:00Z', status: 'ready' }
const analysis = { document_summary: 'An uploaded agreement.', overall_risk: 'high', engine: 'test-engine', disclaimer: 'Human review required.', report: { classifier_model_ids: ['test-classifier'] }, findings: [{ id: 'warranty', title: 'Warranty requires review', category: 'Warranty', severity: 'high', excerpt: 'twelve months', explanation: 'Compare against the approved playbook.', recommendation: 'Confirm the required duration.', grounding_status: 'verified', citations: [{ title: 'Approved playbook', url: 'https://example.org/playbook', section: 'Warranty', excerpt: 'The required warranty duration.', verification_status: 'retrieved_evidence' }] }] }
function json(body: unknown) { return Promise.resolve(new Response(JSON.stringify(body), { status: 200, headers: { 'Content-Type': 'application/json' } })) }
function mockApi(documents: unknown[] = [], custom?: (url: string, init?: RequestInit) => ReturnType<typeof json> | undefined) {
  return vi.spyOn(globalThis, 'fetch').mockImplementation((input, init) => {
    const url = String(input)
    const override = custom?.(url, init)
    if (override) return override
    if (url.endsWith('/api/auth/login')) return json({ access_token: 'test-token', token_type: 'bearer' })
    if (url.endsWith('/documents')) return json(documents)
    if (url.endsWith('/documents/document-1')) return json(doc)
    if (url.includes('/library?')) return json({ corpus: null, evidence: [], documents: [], catalog: [{ id: 'far', title: 'FAR Part 52', url: 'https://www.acquisition.gov/far/part-52', authority: 'Official', category: 'Federal rules' }] })
    if (url.endsWith('/connections')) return json({ connections: [], shared_folder_available: false, sharepoint_available: false, automatic_sync_seconds: 0, persistence: 'dynamodb', security_domain: 'demo' })
    return json([])
  })
}
async function login() {
  const user = userEvent.setup()
  render(<App />)
  await user.type(screen.getByLabelText(/workspace password/i), 'test-password')
  await user.click(screen.getByRole('button', { name: /enter workspace/i }))
  await screen.findByRole('heading', { name: /your contract workspace/i })
  return user
}
describe('Connected Lens workspace', () => {
  beforeEach(() => { vi.spyOn(window, 'scrollTo').mockImplementation(() => {}) })
  afterEach(() => { cleanup(); apiClient.logout(); vi.restoreAllMocks() })
  it('uses Kana Legal branding on sign-in and the workspace', async () => {
    mockApi()
    const user = userEvent.setup()
    render(<App />)
    expect(screen.getByText('Kana Legal')).toBeInTheDocument()
    expect(screen.getByRole('img', { name: 'Kana Systems' })).toHaveAttribute('src', expect.stringContaining('kana-systems-logo.png'))
    await user.type(screen.getByLabelText(/workspace password/i), 'test-password')
    await user.click(screen.getByRole('button', { name: /enter workspace/i }))
    await screen.findByRole('heading', { name: /your contract workspace/i })
    expect(screen.getByText('Legal', { selector: 'b' })).toBeInTheDocument()
    expect(screen.getByRole('img', { name: 'Kana Systems' })).toBeInTheDocument()
    expect(screen.queryByText('Acquisition Lens')).not.toBeInTheDocument()
  })
  it('authenticates and loads only persisted documents without seeded samples', async () => {
    const fetch = mockApi([doc])
    await login()
    expect(await screen.findByText(doc.title)).toBeInTheDocument()
    const call = fetch.mock.calls.find(([url]) => String(url).endsWith('/documents'))
    expect((call?.[1]?.headers as Record<string, string>).Authorization).toBe('Bearer test-token')
    expect(fetch.mock.calls.some(([url]) => String(url).includes('/demo/'))).toBe(false)
    expect(localStorage).toHaveLength(0)
    expect(sessionStorage).toHaveLength(0)
  })
  it('keeps contracts and indexes compact while search can find a collapsed item', async () => {
    const documents = Array.from({ length: 13 }, (_, i) => ({ ...doc, id: `doc-${i}`, title: `Agreement ${i + 1}` }))
    mockApi(documents, url => url.includes('/library?') ? json({ corpus: null, evidence: [], documents, catalog: [] }) : undefined)
    const user = await login()
    expect(document.querySelector('.workspace-topbar')).toBeNull()
    expect(screen.getAllByRole('button', { name: /Agreement/ })).toHaveLength(10)
    await user.click(screen.getByRole('button', { name: 'Show 3 more contracts' }))
    expect(screen.getByRole('region', { name: 'Additional contracts' })).toHaveClass('compact-list-overflow')
    expect(screen.getAllByRole('button', { name: /Agreement/ })).toHaveLength(13)
    await user.click(screen.getByRole('button', { name: 'Show fewer contracts' }))
    await user.type(screen.getByRole('textbox', { name: 'Find a contract' }), 'Agreement 13')
    expect(screen.getAllByRole('button', { name: /Agreement/ })).toHaveLength(1)
    expect(screen.getByRole('button', { name: /Agreement 13/ })).toBeVisible()
    await user.click(screen.getByRole('button', { name: 'Sources' }))
    await screen.findByRole('heading', { name: 'Your indexed documents' })
    expect(screen.getAllByRole('button', { name: /Agreement/ })).toHaveLength(10)
    await user.click(screen.getByRole('button', { name: 'Show 3 more documents' }))
    expect(screen.getByRole('button', { name: /Agreement 13/ })).toBeVisible()
  })
  it('validates input and saves the actual supplied text before reviewing', async () => {
    const fetch = mockApi([], (url, init) => url.endsWith('/documents') && init?.method === 'POST' ? json(doc) : undefined)
    const user = await login()
    await user.click(screen.getByRole('button', { name: /add contract/i }))
    await user.type(screen.getByLabelText(/document title/i), doc.title)
    await user.type(screen.getByLabelText(/^contract text$/i), 'Too short')
    await user.click(screen.getByRole('button', { name: /save to workspace/i }))
    expect(await screen.findByRole('alert')).toHaveTextContent(/at least 80 characters/i)
    await user.clear(screen.getByLabelText(/^contract text$/i))
    await user.type(screen.getByLabelText(/^contract text$/i), doc.text)
    await user.click(screen.getByRole('button', { name: /save to workspace/i }))
    expect(await screen.findByRole('heading', { name: doc.title })).toBeInTheDocument()
    const save = fetch.mock.calls.find(([url, init]) => String(url).endsWith('/documents') && init?.method === 'POST')
    expect(JSON.parse(save?.[1]?.body as string)).toEqual({ title: doc.title, text: doc.text, category: 'contract' })
    expect(screen.getByRole('button', { name: /set up review/i })).toBeInTheDocument()
  })
  it('fails closed when authentication is unavailable', async () => {
    vi.spyOn(globalThis, 'fetch').mockRejectedValue(new TypeError('offline'))
    const user = userEvent.setup()
    render(<App />)
    await user.type(screen.getByLabelText(/workspace password/i), 'password')
    await user.click(screen.getByRole('button', { name: /enter workspace/i }))
    expect(await screen.findByRole('alert')).toHaveTextContent(/local api is unavailable/i)
    expect(screen.queryByRole('navigation')).not.toBeInTheDocument()
  })
  it('groups all six workspaces under four destinations without losing access', async () => {
    mockApi()
    const user = await login()
    expect(within(screen.getByRole('navigation', { name: 'Main navigation' })).getAllByRole('button')).toHaveLength(4)
    await user.click(screen.getByRole('button', { name: /^sources$/i }))
    await screen.findByRole('heading', { name: /source library/i })
    await user.click(screen.getByRole('button', { name: /available sources/i }))
    expect(await screen.findByText('FAR Part 52')).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /data connections/i }))
    expect(await screen.findByText(/dynamodb/i)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /^knowledge$/i }))
    expect(await screen.findByRole('heading', { name: /reviewed records/i })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /entities & relationships/i }))
    expect(await screen.findByRole('heading', { name: /entities & relationships/i })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /reviewed records/i }))
    expect(await screen.findByRole('heading', { name: /reviewed records/i })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /target objects/i })).not.toBeInTheDocument()
  })
  it('collapses by keyboard, keeps named navigation usable, and expands without losing context', async () => {
    mockApi()
    const user = await login()
    const toggle = screen.getByRole('button', { name: 'Collapse sidebar' })
    expect(toggle.closest('.sidebar-controls')?.nextElementSibling).toHaveClass('sidebar-bottom')
    expect(document.querySelector('.sidebar-header .sidebar-toggle')).toBeNull()
    toggle.focus()
    await user.keyboard('{Enter}')
    expect(screen.getByRole('button', { name: 'Expand sidebar' })).toHaveAttribute('aria-expanded', 'false')
    expect(document.querySelector('.lens-workspace')).toHaveClass('sidebar-collapsed')
    await user.click(screen.getByRole('button', { name: 'Sources' }))
    await user.click(screen.getByRole('button', { name: 'Data connections' }))
    expect(screen.getByRole('button', { name: 'Sources' })).toHaveAttribute('aria-current', 'page')
    expect(document.getElementById('workspace-main')).toHaveFocus()
    await user.click(screen.getByRole('button', { name: 'Expand sidebar' }))
    expect(document.querySelector('.lens-workspace')).not.toHaveClass('sidebar-collapsed')
    expect(screen.getByRole('heading', { name: 'Data connections' })).toBeInTheDocument()
    expect(document.querySelector('.brand-name')).toHaveTextContent('Kana Legal')
    expect(document.querySelector('.brand-name br')).toBeNull()
    expect(window.scrollTo).toHaveBeenCalledWith({ top: 0, behavior: 'instant' })
  })
  it('defaults to configured SharePoint and can check and save the actual connection', async () => {
    const fetch = mockApi([], (url, init) => {
      if (url.endsWith('/connections') && init?.method !== 'POST') return json({ connections: [], sharepoint_available: true, shared_folder_available: false, automatic_sync_seconds: 900, persistence: 'dynamodb', security_domain: 'demo' })
      if (url.endsWith('/connections/sharepoint/check')) return json({ site: 'Approved site', library: 'Documents', connected: true })
      if (url.endsWith('/connections') && init?.method === 'POST') return json({ id: 'connection-1' })
    })
    const user = await login()
    await user.click(screen.getByRole('button', { name: 'Sources' }))
    await user.click(screen.getByRole('button', { name: 'Data connections' }))
    await waitFor(() => expect(screen.getByLabelText('Source type')).toHaveValue('sharepoint'))
    await user.click(screen.getByRole('button', { name: 'Test SharePoint access' }))
    expect(await screen.findByRole('status')).toHaveTextContent('Approved site / Documents: connected')
    await user.type(screen.getByLabelText('Name'), 'Original contracts')
    await user.click(screen.getByRole('button', { name: 'Save connection' }))
    const save = fetch.mock.calls.find(([url, init]) => String(url).endsWith('/connections') && init?.method === 'POST')
    expect(JSON.parse(save?.[1]?.body as string)).toEqual({ name: 'Original contracts', provider: 'sharepoint', folder: '', category: 'reference' })
    expect(document.querySelector('.connection-setup .sharepoint-check')).toBeInTheDocument()
    expect(document.querySelector('.connection-setup form')).toBeInTheDocument()
  })
  it('renders saved findings safely and retains contract context in follow-up questions', async () => {
    const hostile = '<img src=x onerror="alert(1)">'
    const questions: unknown[] = []
    const fetch = mockApi([doc], (url, init) => {
      if (url.endsWith('/reviews')) return json([{ id: 'review-1', document_id: doc.id, document_version: doc.version, decision: 'draft', revision: 1, note: '', analysis: { ...analysis, findings: [{ ...analysis.findings[0], title: hostile }] } }])
      if (url.endsWith('/questions')) {
        if (init?.method === 'POST') questions.push({ id: 'question-1', document_id: doc.id, query: 'What warranty applies?', response: { answer: 'Grounded answer from the service.', synthesis_mode: 'test-engine', statements: [], evidence: [] } })
        return json(questions)
      }
    })
    const user = await login()
    await user.click(await screen.findByText(doc.title))
    expect(await screen.findByRole('heading', { name: hostile })).toBeInTheDocument()
    expect(document.querySelector('img[src="x"]')).toBeNull()
    await user.click(screen.getByRole('tab', { name: /ask this contract/i }))
    await user.type(screen.getByLabelText(/question or drafting request/i), 'What warranty applies?')
    await user.click(screen.getByRole('button', { name: /ask \/ generate/i }))
    expect(await screen.findByText('Grounded answer from the service.')).toBeInTheDocument()
    const call = fetch.mock.calls.find(([url, init]) => String(url).endsWith('/questions') && init?.method === 'POST')
    expect(JSON.parse(call?.[1]?.body as string)).toMatchObject({ document_id: doc.id, query: 'What warranty applies?', mode: 'answer' })
  })
  it('clears credentials on sign out', async () => {
    const fetch = mockApi()
    const user = await login()
    await user.click(screen.getByRole('button', { name: /sign out/i }))
    await waitFor(() => expect(screen.getByLabelText(/workspace password/i)).toBeInTheDocument())
    await apiClient.getSample()
    const call = fetch.mock.calls.at(-1)
    expect((call?.[1]?.headers as Record<string, string>).Authorization).toBeUndefined()
  })
  it('renews an expired session without losing the open form or replaying a save', async () => {
    const fetch = mockApi([], (url, init) => url.endsWith('/documents') && init?.method === 'POST'
      ? Promise.resolve(new Response(JSON.stringify({ detail: 'Session expired' }), { status: 401 })) : undefined)
    const user = await login()
    await user.click(screen.getByRole('button', { name: /add contract/i }))
    await user.type(screen.getByLabelText(/document title/i), 'Unsaved mission agreement')
    await user.type(screen.getByLabelText(/^contract text$/i), doc.text)
    await user.click(screen.getByRole('button', { name: /save to workspace/i }))
    const dialog = await screen.findByRole('dialog', { name: /resume your workspace/i })
    expect(document.querySelector('.lens-workspace')).toHaveAttribute('inert')
    await user.type(within(dialog).getByLabelText(/workspace password/i), 'test-password')
    await user.tab()
    expect(within(dialog).getByRole('button', { name: 'Resume workspace' })).toHaveFocus()
    await user.tab()
    expect(within(dialog).getByLabelText(/workspace password/i)).toHaveFocus()
    await user.click(within(dialog).getByRole('button', { name: 'Resume workspace' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(screen.getByLabelText(/document title/i)).toHaveValue('Unsaved mission agreement')
    expect(screen.getByLabelText(/^contract text$/i)).toHaveValue(doc.text)
    expect(document.querySelector('.lens-workspace')).not.toHaveAttribute('inert')
    expect(document.getElementById('workspace-main')).toHaveFocus()
    const saves = fetch.mock.calls.filter(([url, init]) => String(url).endsWith('/documents') && init?.method === 'POST')
    expect(saves).toHaveLength(1)
  })
})
